[package]
name = "dummy_os"
version = "0.1.0"
authors = ["Brendan Long <bccbrendan@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "*"
spin = "*"
[dependencies.multiboot2]
git = "https://github.com/phil-opp/multiboot2-elf64"
